### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by apmcguigan** [apmcguigan/Benjamin-Interiors#1]
- [x] Header Social Icons
- [x] Footer Font resize
- [x] Set up Netlify CMS for blog
- [x] Header Current page does not change color on hover
- [x] blogs clean up templates
- [x] About Navigation button links to About on homepage. 
- [x] Delete about page
- [x] Button text font color
- [x] Insta grid link to Insta posts. Fade on hover
- [x] Contact page, remove spaces between Paragraph tags
- [x] contact page, mark required fields
- [x] Thanks page after contact form. 
- [x] Lighthouse optimizations/Image compression
- [x] Insta Grid pictures resizing on smaller screens
- [x] Fix blog prev/next buttons linking to deleted posts
- [x] README
- [x] Lighthouse accessibility fixes
- [x] Error/404 page styling
- [x] Google analytics
- [ ] Replace Fav icon
- [ ] SEO Description, remove required
- [ ] Services Page { Last }
- [ ] Contact form styling (Fine as is, not important)
- [ ] Remove Grey BG
- [ ] Pick new Primary Color
 ----
With Ben
- [x] Netlify CMS account for Ben
- [x] Netlify Form Email forwarding
- [x] Contact me blurb
- [ ] Register on google search console
- [ ] Write About section
- [ ] Write Costs breakdown
- [ ]  2 more blog posts
